/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaServidorAberto;
import  javax.swing.*;
/**
 *
 * @author Usuario
 */
public class TelaServidorAberta extends JFrame {

    /**
     * Creates new form HomeFechado
     */
    public TelaServidorAberta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jblTitulo = new JLabel();
        jblPorta = new JLabel();
        btnFechar = new JButton();
        txtPortaServidor = new JTextField();
        jblTextoServidorAberto = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jblTitulo.setFont(new Font("Tahoma", 0, 18)); // NOI18N
        jblTitulo.setText("Espaço do Servidor");

        jblPorta.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        jblPorta.setText("Insira a porta (Padrão: 8888)");

        btnFechar.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        btnFechar.setText("Fechar");

        jblTextoServidorAberto.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        jblTextoServidorAberto.setForeground(new Color(51, 204, 0));
        jblTextoServidorAberto.setText("Servidor Aberto!");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jblPorta)
                    .addComponent(txtPortaServidor, GroupLayout.PREFERRED_SIZE, 327, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jblTitulo)
                        .addGap(122, 122, 122))
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFechar)
                        .addGap(162, 162, 162))))
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblTextoServidorAberto)
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jblTitulo)
                .addGap(36, 36, 36)
                .addComponent(jblPorta)
                .addGap(18, 18, 18)
                .addComponent(txtPortaServidor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jblTextoServidorAberto)
                .addGap(18, 18, 18)
                .addComponent(btnFechar)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */


        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaServidorAberta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnFechar;
    private JPanel jPanel1;
    private JLabel jblPorta;
    private JLabel jblTextoServidorAberto;
    private JLabel jblTitulo;
    private JTextField txtPortaServidor;
    // End of variables declaration//GEN-END:variables
}
